version: '3.7'
services:
  test:
    image: node:12.16.1
    command: node --version
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.33
    entrypoint: ["sh","-c"]
    command:
      - |
        echo "PORT=$$PORT"
        echo "Hello World!"
    environment:
      - PORT=8888